### ISSUE TITLE
There should be no import/export when symmetric is used

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#10]
The symmetric passphrase should be used. no key import export is necessary. The symmetric key is not a key but just a regular password.

https://github.com/deep-diver/fb-group-post-fetcher/blob/b93fa008cd334ce3b168fda41955c8e6fdf654eb/.github/workflows/main.yml#L19-L25

**Comment by deep-diver** [comment]
grrrr...

I have tried the original way multiple times, and I got an error like
```
gpg: decryption failed: Bad session key
```

Is there a way to test GithubAction in local environment?

**Comment by kkweon** [comment]
GPG takes some time to understand.

For a reference, this is how I run
https://github.com/dl4ab/DFAB-Archiver-slackbot/blob/f03dc361346efa5e6846f561464939f43c50192b/.github/workflows/cronjob.yaml#L23-L33

**Comment by kkweon** [comment]
You probably have to reencrypt it again. The error is because something is out of sync between how it's encrypted and how it's decrypted. Try ascii (--armour) encrypt as well. I have noticed there are line ending (CRLF) issues in some files. This may have affected the binary.
