### ISSUE TITLE
Add a link to the post in the newsletter

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#11]
So a user can see the actual post in FB.

**Comment by deep-diver** [comment]
It's tiny and ugly. But there is a link!

<img width="241" alt="Screen Shot 2020-06-22 at 4 45 45 PM" src="https://user-images.githubusercontent.com/26025527/85261896-e1db3880-b4a7-11ea-8420-2e95f103daba.png">

**Comment by kkweon** [comment]
아하 못봤네요
