### ISSUE TITLE
Undefined variable 'attatchments' 

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#13]
```
************* Module lib.model.facebook_post
lib/model/facebook_post.py:33:34: E0602: Undefined variable 'attatchments' (undefined-variable)
```

https://github.com/deep-diver/fb-group-post-fetcher/blob/1cca1b606efeca58ca116cf326b6b034b37b36f6/lib/model/facebook_post.py#L32-L33

**Comment by deep-diver** [comment]
they are mistyped... 
I have fixed them now
