### ISSUE TITLE
char count ellipsis is not working

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#14]
The second post has nearly 7,000 chars. 

https://groups.google.com/forum/?fbclid=IwAR08kfW4Nma8lO8-cJQwu1PEYHjtt9mRgWzN8yUzFUtKmZ3xdFqeOwBriKo#!topic/tfkr-newsletter-mailing-list/yQMMk-dDPXk

**Comment by deep-diver** [comment]
right. I noticed that too.
I could't find the cause and flaws from my code at the moment.
I will inspect more closely a little later...

**Comment by deep-diver** [comment]
I have fixed and tested, and it seems work. 

![Screen Shot 2020-06-23 at 11 31 05 PM](https://user-images.githubusercontent.com/26025527/85416794-da03bd00-b5a9-11ea-83c9-2159508b1fe1.png)
