### ISSUE TITLE
Mention Python version used for the script

### ISSUE THREAD

**Issue by ju-sh** [deep-diver/fb-group-post-fetcher#16]
Hi. It would be helpful for others who may be interested in this work to know which Python version can be used with it.

From a quick glance at the code, looks like Python>=3.8 is required.

Maybe the version info can be mentioned in the README?

**Comment by deep-diver** [comment]
you are right.
however, all the dependencies are specified in Pipfile like below.

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = false

[dev-packages]

[packages]
pytz = "*"
aiohttp = "*"
python-dotenv = "*"
markdown2 = "*"
jinja2 = "*"
premailer = "*"

[requires]
python_version = "3.8"
```

**Comment by ju-sh** [comment]
Ah.. had not seen that. :+1:
