### ISSUE TITLE
Use premailer instead of inline styling

### ISSUE THREAD

**Issue by kkweon** [deep-diver/fb-group-post-fetcher#3]
https://pypi.org/project/premailer/

**Comment by deep-diver** [comment]
this is really cool library.

I will probably use `premailer` with any good email template project. And of course with Jinja as well. 
I am trying to find one good email template project, and I have found [Cerberus](https://github.com/TedGoas/Cerberus). This choice is not fixed, and I could make my own template from scratch if needed. 

Thanks!
